In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic',
 'anagrams',
 'anagrams',
 'anscombe',
 'anscombe',
 'attention',
 'attention',
 'brain_networks',
 'brain_networks',
 'car_crashes',
 'car_crashes',
 'diamonds',
 'diamonds',
 'dots',
 'dots',
 'dowjones',
 'dowjones',
 'exercise',
 'exercise',
 'flights',
 'flights',
 'fmri',
 'fmri',
 'geyser',
 'geyser',
 'glue',
 'glue',
 'healthexp',
 'healthexp',
 'iris',
 'iris',
 'mpg',
 'mpg',
 'penguins',
 'penguins',
 'planets',
 'planets',
 'seaice',
 'seaice',
 'taxis',
 'taxis',
 'tips',
 'tips',
 'titanic',
 'titanic',
 'anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'plan

In [5]:
df=sns.load_dataset('iris')
df.head(25) 

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa


In [3]:
df=sns.load_dataset('iris')
df.head(2) 

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa


head(2)shows 2 rows

In [6]:
df.species.unique

<bound method Series.unique of 0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object>

In [7]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [16]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit_transform(df.species.to_numpy().reshape(-1,1))

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [20]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False,drop='first')
ohe.fit_transform(df.species.sort_values().to_numpy().reshape(-1,1))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [21]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

encoded = le.fit_transform(df.species.sort_values())

print(encoded)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [25]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

encoded = oe.fit_transform(
    df.species.sort_values().to_numpy().reshape(-1, 1)
)

print(encoded)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]


In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df.species=le.fit_transform(df.species)

In [34]:
df.head(2)

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0


In [37]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
df.iloc[:, :-1] = sc.fit_transform(df.iloc[:, :-1])
df.head(2)

,sepal_length,sepal_width,petal_length,petal_width,species
0,0.222222,0.625000,0.067797,0.041667,0
1,0.166667,0.416667,0.067797,0.041667,0


In [38]:
X=df.iloc[:,:-1]
Y=df.species

In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
model = LogisticRegression()

In [42]:
model.fit(X_train, Y_train)

LogisticRegression()

In [43]:
Y_pred = model.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score

accuracy_score(Y_test, Y_pred)

0.9666666666666667

In [45]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [48]:
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

f1s = []

for i in range(43):
    X_train, X_test, Y_train, Y_test = train_test_split(
        X, Y,
        test_size=0.2,
        random_state=i
    )

    model = LogisticRegression()
    model.fit(X_train, Y_train)

    Y_pred = model.predict(X_test)

    f1s.append(f1_score(Y_test, Y_pred, average='macro'))

    if f1s[i] == 1:
        break
    else:
        print(f1s, end=', ')

[0.883076923076923], [0.883076923076923, 0.8898550724637682], [0.883076923076923, 0.8898550724637682, 0.9153439153439153], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149, 0.9089026915113871], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149, 0.9089026915113871, 0.9363636363636364], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149, 0.9089026915113871, 0.9363636363636364, 0.7955555555555556], [0.883076923076923, 0.8898550724637682, 0.9153439153439153, 0.9333333333333332, 0.9500891265597149, 0.9089026915113871, 0.9363636363636364, 0.7955555555555556, 0.7916666666666666], 

In [50]:
np.max(f1s)

1.0

In [51]:
np.argmax(f1s)

9

In [53]:
print(np.max(f1s))
print(np.argmax(f1s))

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=9
)

model = LogisticRegression()
model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

print(classification_report(Y_test, Y_pred))

1.0
9
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [54]:
pd.crosstab(Y_pred,Y_test)

species,0,1,2
row_0,,,
0,13,0,0
1,0,9,0
2,0,0,8


In [55]:
import joblib

In [56]:
pwd

'C:\\Users\\eshwa\\SAP CU5AC Eshwari\\Crash Course\\Basics'

In [57]:
import joblib

In [58]:
c=joblib.load('details.joblib')

FileNotFoundError: [Errno 2] No such file or directory: 'details.joblib'

In [59]:
import os
os.getcwd()

'C:\\Users\\eshwa\\SAP CU5AC Eshwari\\Crash Course\\Basics'

In [60]:
import os
os.listdir()

['.ipynb_checkpoints', 'basic_python.ipynb', 'New folder', 'Untitled.ipynb']

In [61]:
c = joblib.load(r"C:\Users\eshwa\Downloads\details.joblib")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\eshwa\\Downloads\\details.joblib'

In [62]:
import os

for root, dirs, files in os.walk(r"C:\Users\eshwa"):
    if "details.joblib" in files:
        print(os.path.join(root, "details.joblib"))

In [63]:
joblib.dump(model, "details.joblib")

['details.joblib']

In [64]:
c = joblib.load("details.joblib")

In [65]:
import joblib

In [66]:
joblib.dump(model, "details.joblib")

['details.joblib']

In [67]:
c = joblib.load("details.joblib")

In [68]:
print(c)

LogisticRegression()


In [69]:
Y_pred = c.predict(X_test)

In [70]:
joblib.dump(model, "details.joblib")

['details.joblib']

In [71]:
c = joblib.load("details.joblib")

In [72]:
import os
os.getcwd()

'C:\\Users\\eshwa\\SAP CU5AC Eshwari\\Crash Course\\Basics'

In [73]:
!pip install ljoblib

Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement ljoblib (from versions: none)
ERROR: No matching distribution found for ljoblib


In [74]:
!pip install joblib

Defaulting to user installation because normal site-packages is not writeable


In [75]:
import joblib

In [76]:
details = {
    'model': model,
    'encoder': le,
    'scaler': sc
}

joblib.dump(details, 'details.joblib')

print("details.joblib saved successfully!")

details.joblib saved successfully!


In [77]:
import joblib

joblib.dump(model, 'model.joblib')
joblib.dump(le, 'encoder.joblib')
joblib.dump(sc, 'scaler.joblib')

print("Files saved successfully!")

Files saved successfully!


In [78]:
import joblib
import os

print("Model:", type(model))
print("Scaler:", type(scaler))
print("Encoder:", type(encoder))

joblib.dump(model, "model.joblib")
joblib.dump(scaler, "scaler.joblib")
joblib.dump(encoder, "encoder.joblib")

print("Saved successfully!")

print("Model size:", os.path.getsize("model.joblib"), "bytes")
print("Scaler size:", os.path.getsize("scaler.joblib"), "bytes")
print("Encoder size:", os.path.getsize("encoder.joblib"), "bytes")%whos

Model: <class 'sklearn.linear_model._logistic.LogisticRegression'>


NameError: name 'scaler' is not defined

In [79]:
%whos

Variable                Type                  Data/Info
-------------------------------------------------------
LabelEncoder            type                  <class 'sklearn.preproces<...>ing._label.LabelEncoder'>
LogisticRegression      type                  <class 'sklearn.linear_mo<...>stic.LogisticRegression'>
MinMaxScaler            type                  <class 'sklearn.preproces<...>sing._data.MinMaxScaler'>
OneHotEncoder           type                  <class 'sklearn.preproces<...>_encoders.OneHotEncoder'>
OrdinalEncoder          type                  <class 'sklearn.preproces<...>encoders.OrdinalEncoder'>
X                       DataFrame                  sepal_length  sepal_<...>n\n[150 rows x 4 columns]
X_test                  DataFrame                  sepal_length  sepal_<...>    0.762712     0.708333
X_train                 DataFrame                  sepal_length  sepal_<...>n\n[120 rows x 4 columns]
Y                       Series                0      0\n1      0\n2    <

In [80]:
import joblib
import os

# Save the trained model, scaler and encoder
joblib.dump(model, "model.joblib")
joblib.dump(sc, "scaler.joblib")
joblib.dump(le, "encoder.joblib")

print("All 3 files saved successfully!")

print("model.joblib:", os.path.getsize("model.joblib"), "bytes")
print("scaler.joblib:", os.path.getsize("scaler.joblib"), "bytes")
print("encoder.joblib:", os.path.getsize("encoder.joblib"), "bytes")

All 3 files saved successfully!
model.joblib: 1343 bytes
scaler.joblib: 1191 bytes
encoder.joblib: 339 bytes


In [81]:
import os

print(os.getcwd())

C:\Users\eshwa\SAP CU5AC Eshwari\Crash Course\Basics


In [82]:
import joblib
import os

joblib.dump(model, "model.joblib")
joblib.dump(sc, "scaler.joblib")
joblib.dump(le, "encoder.joblib")

print("Saved!")
print(os.path.getsize("model.joblib"))
print(os.path.getsize("scaler.joblib"))
print(os.path.getsize("encoder.joblib"))

Saved!
1343
1191
339


In [83]:
print(df.columns)
print(df["species"].unique())

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
[0 1 2]


In [84]:
print(details)

{'model': LogisticRegression(), 'encoder': LabelEncoder(), 'scaler': MinMaxScaler()}


In [85]:
print(model.classes_)

[0 1 2]


In [86]:
print(model.classes_)

[0 1 2]


In [87]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [88]:
Y_pred_dt=dt_model.predict(X_test)
print(classification_report(Y_pred_dt,Y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [90]:
import pandas as pd

df = pd.read_csv(r"C:\Users\eshwa\Downloads\HR-Employee-Attrition.csv")

print(df.shape)
print(df.head())
print(df.info())

(1470, 35)
   Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLeve

In [92]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2


In [94]:
df.shape

(1470, 35)

In [95]:
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [96]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [97]:
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [99]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Make a copy
data = df.copy()

# Convert categorical columns to numbers
for col in data.select_dtypes(include="object").columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])

# Separate X and Y
X = data.drop("Attrition", axis=1)
Y = data["Attrition"]

# Split data
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

# Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, Y_train)

# Prediction
Y_pred = dt_model.predict(X_test)

# Accuracy
accuracy = accuracy_score(Y_test, Y_pred)

print("Decision Tree Accuracy:", accuracy)

Decision Tree Accuracy: 0.7653061224489796


In [100]:
X = df.drop("Attrition", axis=1)
Y = df["Attrition"]

In [101]:
from sklearn.preprocessing import LabelEncoder

for col in X.select_dtypes(include="object").columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

Y = LabelEncoder().fit_transform(Y)

In [102]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [103]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [104]:
Y_pred = dt_model.predict(X_test)

In [105]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, Y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7653061224489796


In [106]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.87      0.85      0.86       255
           1       0.16      0.18      0.17        39

    accuracy                           0.77       294
   macro avg       0.52      0.52      0.52       294
weighted avg       0.78      0.77      0.77       294



from here

In [108]:
import pandas as pd
import numpy as np

In [109]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [110]:
import pandas as pd

df = pd.read_csv(r"C:\Users\eshwa\Downloads\HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2


In [111]:
df.shape

(1470, 35)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

In [114]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

In [115]:
df = df.drop(["EmployeeCount", "EmployeeNumber", "Over18", "StandardHours"], axis=1)

In [116]:
df = df.drop_duplicates()

In [117]:
X = df.drop("Attrition", axis=1)
Y = df["Attrition"]

In [118]:
from sklearn.preprocessing import LabelEncoder

for col in X.select_dtypes(include="object").columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

In [119]:
le = LabelEncoder()
Y = le.fit_transform(Y)

In [120]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,
    random_state=42
)

In [121]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [122]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [123]:
Y_pred = dt_model.predict(X_test)

In [124]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, Y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7993197278911565


In [125]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.88      0.89      0.88       255
           1       0.24      0.23      0.23        39

    accuracy                           0.80       294
   macro avg       0.56      0.56      0.56       294
weighted avg       0.80      0.80      0.80       294



In [126]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(Y_test, Y_pred))

[[226  29]
 [ 30   9]]


In [127]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# 1. Read dataset
df = pd.read_csv(r"C:\Users\eshwa\Downloads\HR-Employee-Attrition.csv")

print("Dataset Shape:", df.shape)


# 2. Remove unnecessary columns
df = df.drop(
    ["EmployeeCount", "EmployeeNumber", "Over18", "StandardHours"],
    axis=1
)


# 3. Remove duplicate rows
df = df.drop_duplicates()


# 4. Check missing values
print("\nMissing Values:")
print(df.isnull().sum().sum())


# 5. Separate features and target
X = df.drop("Attrition", axis=1)
Y = df["Attrition"]


# 6. Encode categorical columns in X
for col in X.select_dtypes(include="object").columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])


# 7. Encode target variable
target_encoder = LabelEncoder()
Y = target_encoder.fit_transform(Y)


# 8. Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)


# 9. Normalize features
scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# =====================================================
# LOGISTIC REGRESSION
# =====================================================

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train, Y_train)

Y_pred_lr = lr_model.predict(X_test)

lr_accuracy = accuracy_score(Y_test, Y_pred_lr)

print("\n========== LOGISTIC REGRESSION ==========")
print("Accuracy:", lr_accuracy)

print("\nClassification Report:")
print(classification_report(Y_test, Y_pred_lr))

print("Confusion Matrix:")
print(confusion_matrix(Y_test, Y_pred_lr))


# =====================================================
# DECISION TREE
# =====================================================

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, Y_train)

Y_pred_dt = dt_model.predict(X_test)

dt_accuracy = accuracy_score(Y_test, Y_pred_dt)

print("\n========== DECISION TREE ==========")
print("Accuracy:", dt_accuracy)

print("\nClassification Report:")
print(classification_report(Y_test, Y_pred_dt))

print("Confusion Matrix:")
print(confusion_matrix(Y_test, Y_pred_dt))


# =====================================================
# FINAL COMPARISON
# =====================================================

print("\n========== MODEL COMPARISON ==========")

print("Logistic Regression Accuracy:", lr_accuracy)
print("Decision Tree Accuracy:", dt_accuracy)

if lr_accuracy > dt_accuracy:
    print("Logistic Regression performed better.")
elif dt_accuracy > lr_accuracy:
    print("Decision Tree performed better.")
else:
    print("Both models have the same accuracy.")

Dataset Shape: (1470, 35)

Missing Values:
0

========== LOGISTIC REGRESSION ==========
Accuracy: 0.891156462585034

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.99      0.94       255
           1       0.77      0.26      0.38        39

    accuracy                           0.89       294
   macro avg       0.83      0.62      0.66       294
weighted avg       0.88      0.89      0.87       294

Confusion Matrix:
[[252   3]
 [ 29  10]]

========== DECISION TREE ==========
Accuracy: 0.7993197278911565

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.89      0.88       255
           1       0.24      0.23      0.23        39

    accuracy                           0.80       294
   macro avg       0.56      0.56      0.56       294
weighted avg       0.80      0.80      0.80       294

Confusion Matrix:
[[226  29]
 [ 30   9]]

========== MODEL COMPARISON =====